version: "3"

services:

  neo4j:
    image: neo4j:4.4.8-community
    volumes:
      - ./logs:/logs
      - ./import:/import
      - ./plugins:/plugins
      - data:/data
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      NEO4J_AUTH: neo4j/neo4jj
      NEO4J_dbms_memory_pagecache_size: 512M
      NEO4J_dbms.directories.import: /import

volumes:
  data:
