version: "3"

services:

    neo4j:
        image: neo4j:3.5
        volumes:
            - ./conf:/var/lib/neo4j/conf
            - ./import:/var/lib/neo4j/import
            - ./logs:/var/lib/neo4j/logs
            - ./data:/data
        ports:
            - 7474:7474
            - 7687:7687
